// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCovuSnEHoUHUuIVb-Slv2tzcoRdEhcvMU',
    appId: '1:40875853723:web:7e77eeaa0d665f99da433e',
    messagingSenderId: '40875853723',
    projectId: 'mtaa-signaling-server',
    authDomain: 'mtaa-signaling-server.firebaseapp.com',
    storageBucket: 'mtaa-signaling-server.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0qGYLsAK6_C5O5GV23_OQpe_7lkxWrGE',
    appId: '1:40875853723:android:85bd2dc50fdec437da433e',
    messagingSenderId: '40875853723',
    projectId: 'mtaa-signaling-server',
    storageBucket: 'mtaa-signaling-server.appspot.com',
  );
}
